### PR TITLE
Add support for .NET 6 iOS

### PR DESCRIPTION
**Pull request by frenzibyte**
While I was working towards migrating our projects to target `net6-ios` instead, I've came across this as a major blocker. Supporting .NET 6 iOS didn't take much, but I don't have a MIDI device to check whether it's working (only copying from the Xamarin.iOS project)

### CODE REVIEW

**Comment by atsushieno** [comment]
I haven't tracked those .NET6/iOS changes these days, let me take the pill and blindly merge it. Thanks.

**Comment by frenzibyte** [comment]
Thanks! Publishing a new release today would be appreciated as well.

**Comment by atsushieno** [comment]
Hmm, if I could successfully sign in to Azure DevOps...

image

**Comment by atsushieno** [comment]
Signing in via GitHub does not seem to work for me somehow. I could manage to log in via MS authenticator.

I had to adjust Azure DevOps build pipeline as VS2017 seems to have vanished. Now I switched to Azure Pipeline on macosx-latest (with no change). Then I ran it, and it resulted in this NuGet restore error:

https://atsushieno.visualstudio.com/managed-midi/_build/results?buildId=363&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=758dd57d-3f0a-5dd4-7652-94cac144bdbe

At this state I'm not sure what's causing it. Was it restoring successfully at your environment?

I'm not sure if I want to revert the changes and retry.

**Comment by frenzibyte** [comment]
From the logs it looks to be using MSBuild v15, .NET 6 projects require MSBuild v17 at least. I see you're using `nuget restore`, have you tried using `dotnet restore` instead?

**Comment by atsushieno** [comment]
Okay, thanks. Afterwards I tried a couple of changes without making changes in the codebase but looks like the old SDK are dead overall. I'm not sure how you built your solution but since Azure DevOps does not seem able to build it there, it will not be published until builds get fixed.

**Pull request merged**
