### PR TITLE
Support GitHub Actions

### PR DESCRIPTION
**Pull request by frenzibyte**
Better and modern replacement of Azure Pipelines. I've separated the main solution using solution filters based on the framework, to allow building all projects correctly using different toolings (`dotnet` for .NET Core, `msbuild` for .NET Framework and Xamarin).

This PR features two workflows:
 - CI (`ci.yml`): ensures all project build successfully and uploads a package to the artifacts to allow for local testing, automatically runs on each push to a branch or in a PR.
 - Deployment (`release.yml`): builds all projects, packs, and publishes to NuGet, manually ran.
   - requires preparing a version-named tag on HEAD before launching the workflow, such that the script versions the package using the tag name.
   - requires supplying the API key for NuGet via secret, can be added in Settings -> Secrets -> Actions -> New repository secret, the name of the secret should be `NUGET_API_KEY`.

### CODE REVIEW

**Comment by frenzibyte** [comment]
All done with this PR, should be ready to go.

**Comment by atsushieno** [comment]
Let's see if tagging works as expected...!

**Comment by frenzibyte** [comment]
Note that you have to manually run the "Release" workflow, as it doesn't seem possible to make it always run automatically on tag push (sometimes works sometimes doesn't, pretty weird).

**Comment by atsushieno** [comment]
Yeah, thanks. Running it now.

**Comment by atsushieno** [comment]
It is successfully up. Thanks again!

**Pull request merged**
