### PR TITLE
Add PlaybackCompletedToEnd event (apart from Finished event) and Stop method.

### PR DESCRIPTION
**Pull request by atsushieno**
This should resolve issue #29.

### CODE REVIEW

**Comment by atsushieno** [comment]
@jeroenwalter does this look right for you?

**Comment by atsushieno** [comment]
Apart from the primary issue, we should sort out when "-Async" methods are required and when not...

**Comment by jeroenwalter** [comment]
Looks alright to me. You're missing a test though, the situation that playback is stopped before the end of the midi file is not tested. I.e. 
`Assert.IsTrue (completed);
Assert.IsTrue (!finished);`

Right now I'm trying to figure out how to synchronize my fork with your repository including the new branch. I'm still a noob with git.... :)

**Comment by atsushieno** [comment]
I know - I have a problem with testing that, my virtual time manager design (which is for testing without consuming actual time) needs some improvements (filed as https://github.com/atsushieno/managed-midi/issues/31). There will be additional tests once it's done.

There is no rush for your local merging / creating PRs, git is complicated enough to deal with that ;-) Take your time.

**Pull request merged**
