### PR TITLE
Added, fixed and tested support for Android, iOS, UWP, WPF and Mac  

### PR DESCRIPTION
**Pull request by jaladaGmbH**
For these I have made a lot of changes, have add a default Midi-synthesizer for all systems and made a Xamarin.Forms test project. 

The Linux version is now possible broken because I have no Linux-System for testing. It would be nice to have also a Xamarin.Forms subproject for Linux. 

Best regards
Andreas jalada GmbH

### CODE REVIEW

**Comment by atsushieno** [comment]
Hello, you have some interesting application project based on managed-midi, which is cool :-)

Let me point out some quick general things:

- We ask PRs to keep changes minimum, otherwise it makes code reviews impossible. And the *unnecessary* changes include code style changes. I'm seeing some garbages like `*.nupkg` files included in the PR.
- managed-midi itself is not going to include "application" projects other than samples, especially there are big external dependencies. For example, I leave my [fluidsynth-midi-service](https://github.com/atsushieno/fluidsynth-midi-service) consolidated. It is totally doable because managed-midi can be simply a dependency and only public API is used.
- As a supplemental note, I'm quite unsure if your "general MIDI synthesizer" project is general enough. It depends on some SF2 files and implementation (while I keep my fluidsynth binding outside).
- On a related note, Xamarin.Forms is irrelevant to managed-midi. Even those Xamarin components are designed to be isolated from Xamarin.Forms so that they can be used by Xamarin native (X.Android, X.iOS etc.) projects.
- We basically don't accept API-breaking changes unless it is really needed.
- The changes in the PR include assembly name changes, but managed-midi is basically a solution of shared projects. Those assemblies from the per-platform library projects are designed to be identical across the platforms so that type references to `Commons.Music.Midi.dll` remain valid and accessible on all supported platforms.

Lastly, I should mention that as the project description says the entire project development is actually kind of stopped (because I'm based on Linux and Microsoft is not going to provide first class experience on Linux). You wouldn't see a lot of changes in this project so far. I do use this project for my own and make changes though.

Let me close this PR for now, as I cannot find appropriate way to isolate individual changes and find only one from the changes. Thanks for the PR though! Let me know if you put your changes as an isolated GitHub project (or elsewhere) or create further PRs, I would create some list of users projects on wiki page or README.

**Comment by jaladaGmbH** [comment]
Hello Atsushi Eno,

many thanks for your long answer and I understand your point of view. Also I think it make no sense to integrate my changes into your master, because 300 changes are a lot of stuff. 

But I read also in your answer that you have stopped the development for managed-midi. So I think I should start a new development branch at GitHub, mainly for Android, iOS, MacOS, UWP and WPF because I have no Linux device at the moment. 

To explain my intention for the changes. I plan to use managed-midi inside of one or more Xamarin.Forms projects, so I have made a complex sample project with Xamarin.Forms to test the functionality, which is now part of the branch. I change the API to add observable collections for input and output devices. Also I add a delegate/listener to recognize this changes. 

A default synthesizer make only sense, when it is shown up in the list of output devices and is used as normal device. On WPF and UWP this was easy because Windows add a synthesizer automatically. On Android I add the Midi Driver from Bill the farmer as a service. On iOS and MacOS you need a SoundFont file to use the AVAudioUnitSampler from the Apple SDK. To better understand your code I moved every class in a separate file and changed the project structure to a separate .netstandard project and for every device a specific platform project.... 

To avoid conflicts for existing users I rename the branch to Commons.Music.Midi which you can find now under [https://github.com/jaladaGmbH/Commons.Music.Midi](https://github.com/jaladaGmbH/Commons.Music.Midi) 

I will also made a nuget package with the same name and start with a version number of 2.0.0.  Tell if this is okay for you.

Best regards
Andreas

**Comment by jaladaGmbH** [comment]
Hello Atsushi Eno,

many thanks for your long answer and I understand your point of view. 
Also I think it make no sense to integrate my changes into your master, 
because 300 changes are a lot of stuff.

But I read also in your answer that you have stopped the development for 
managed-midi. So I think I should start a new development branch at 
GitHub, mainly for Android, iOS, MacOS, UWP and WPF because I have no 
Linux device at the moment.

To explain my intention for the changes. I plan to use managed-midi 
inside of one or more Xamarin.Forms projects, so I have made a complex 
sample project with Xamarin.Forms to test the functionality, which is 
now part of the branch. I change the API to add observable collections 
for input and output devices. Also I add a delegate/listener to 
recognize this changes.

A default synthesizer make only sense, when it is shown up in the list 
of output devices and is used as normal device. On WPF and UWP this was 
easy because Windows add a synthesizer automatically. On Android I add 
the Midi Driver from Bill the farmer as a service. On iOS and MacOS you 
need a SoundFont file to use the AVAudioUnitSampler from the Apple SDK. 
To better understand your code I moved every class in a separate file 
and changed the project structure to a separate .netstandard project and 
for every device a specific platform project....

To avoid conflicts for existing users I rename the branch to 
Commons.Music.Midi which you can find now under 
[https://github.com/jaladaGmbH/Commons.Music.Midi](https://github.com/jaladaGmbH/Commons.Music.Midi) 


I will also made a nuget package with the same name and start with a 
version number of 2.0.0.

Tell me if this is okay for you.

Best regards
Andreas

**Comment by atsushieno** [comment]
While you can technically distribute a NuGet package that contains the identical name of assemblies as mine, you cannot really create a nuget packages with the same package ID as mine. And as I mentioned earlier, your assemblies won't work as mine did as you renamed them per platform, which breaks the "bait and swirch" technique used by the shared projects.

I would suggest you to give your own name, not `Commons.Music.Midi` (even adding "-ng", ".Next" would work). Ideally the name should be completely different. Otherwise I will have to make a bold claim that your project is nothing more than just a private fork and has nothing to do with my direction for the next versions, which wouldn't be good for you either.

**Comment by atsushieno** [comment]
> you cannot really create a nuget packages with the same package ID as mine

This is a technical limitation (you know, otherwise the entire NuGet ecosystem would have been full of scam packages).

**Comment by jaladaGmbH** [comment]
Sorry Atsushi Eno,

I want no conflict, I used your project because it is a nice piece of 
software. But I read in your last message that you have stopped 
developing and your project is now deprecated or legacy. That's the only 
reason why I made a new branch and would like to make new packages, to 
show the development goes on.

> While you can technically distribute a NuGet package that contains the 
> identical name of assemblies as mine, you cannot really create a nuget 
> packages with the same package ID as mine.

I'm not stupid. The first thing I changed today was the ID of the 
package in the .nuspec and changed the title from "managed-midi" to 
"Commons.Music.Midi", to avoid any problems for your existing users when 
they update via Nuget-Manager. If you think I should change the name of 
the assemblies to something complete different, I will do this.

> has nothing to do with my direction for the next versions, which 
> wouldn't be good for you either.
It would be nice, when you make a new version of managed-midi. I hope so.

But for the moment tell me what I should do to settle our dispute.

Best regards

Andreas


Am 21.09.2020 um 17:39 schrieb Atsushi Eno:

**Comment by atsushieno** [comment]
I know you have no offence, I trust you. But from package consumers point of view, I'd say Commons.Music.Midi is confusing enough because basically it is identical to my project and that'd be harmful. It is totally legal if you try enough to publicly announce that yours is different from my project, but that'd be just awkward. You can choose any name that implies it's better than old ones (".Improved", ".Evolved", ".NextGen" etc.), just not "exactly the same".

**Comment by jamesdlow** [comment]
@jaladaGmbH did you every release a nuget package with your iOS/Mac changes? I'd like to use something that would work on those platforms.

**Pull request closed without merging**
